name: Automatic Zip Screenshot Scanner

on:
  workflow_dispatch:
    inputs:
      start_id:
        description: 'Start ID'
        required: true
        default: '666'
      end_id:
        description: 'End ID'
        required: true
        default: '700'

permissions: write-all

jobs:
  scan_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Code Fetch Karo
      uses: actions/checkout@v4
      with:
        persist-credentials: true
        fetch-depth: 0

    - name: Python Setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: System Dependencies (FFmpeg)
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Python Packages Install Karo
      run: pip install requests

    - name: Script Nu Run Karo
      env:
        START_ID: ${{ github.event.inputs.start_id }}
        END_ID: ${{ github.event.inputs.end_id }}
      run: python bulk_extractor.py

    - name: Save to GitHub Repository
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # Sirf channels.txt te zip file nu add karo repo vich
        git add channels.txt channel_screenshots.zip
        
        if ! git diff-index --quiet HEAD; then
          git commit -m "Updated channels.txt and zip archive for IDs ${{ github.event.inputs.start_id }}-${{ github.event.inputs.end_id }}"
          git pull --rebase origin main
          git push origin main
        else
          echo "No changes to commit"
        fi
